export type Segment = string | { strong: string }

export type Block =
  | { type: 'p';  text: Segment[] }
  | { type: 'ul'; items: Segment[][] }
  | { type: 'h2'; text: string }

export interface LegalClause {
  id?: string
  num?: string
  heading?: string
  blocks: Block[]
}

export interface LegalSection {
  id: string
  title: string
  clauses: LegalClause[]
}

const s = (text: string): Segment[] => [text]
const b = (strong: string, rest = ''): Segment[] =>
  rest ? [{ strong }, rest] : [{ strong }]

export const SECTIONS: LegalSection[] = [
  // ── TERMS OF SERVICE ───────────────────────────────────────────────────────
  {
    id: 'tos',
    title: 'Meridian Terms of Service',
    clauses: [
      {
        id: 'tos-1', num: '1', heading: 'Acceptance of Terms',
        blocks: [
          { type: 'p', text: s('By creating an account, accessing, or using the Meridian platform ("Service"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree to these Terms, do not use the Service.') },
          { type: 'p', text: s('These Terms constitute a legally binding agreement between you and Solvega Labs LLC, a Utah limited liability company ("Solvega Labs," "we," "us," or "our"). We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.') },
        ],
      },
      {
        id: 'tos-2', num: '2', heading: 'Description of Service',
        blocks: [
          { type: 'p', text: s('Meridian is an AI-powered intelligence platform that monitors user-defined objectives, gathers and synthesizes signals from publicly available information sources, and generates confidence scores, action recommendations, and analytical reports (collectively, "AI Output"). The Service is intended to help users organize, track, and gain perspective on their personal and professional goals.') },
          { type: 'p', text: s("The Service is powered in part by Anthropic's Claude AI models. By using Meridian, you acknowledge that your inputs may be processed by Anthropic's systems in accordance with Anthropic's usage policies.") },
        ],
      },
      {
        id: 'tos-3', num: '3', heading: 'AI Accuracy Disclaimer — Read Carefully',
        blocks: [
          { type: 'p', text: b('Meridian uses artificial intelligence to generate analytical output. AI can make mistakes. The Service may produce output that is inaccurate, incomplete, outdated, or not applicable to your specific situation.') },
          { type: 'p', text: s('Confidence scores generated by Meridian are probabilistic estimates based on available signals at the time of the sweep. They are not predictions of future outcomes and should not be relied upon as such. Signals sourced from third-party providers may themselves be inaccurate, incomplete, or delayed, and Solvega Labs does not verify the accuracy of third-party information.') },
          { type: 'p', text: [{ strong: 'You are responsible for independently verifying any information provided by the Service before acting on it.' }, ' Always apply your own judgment. Solvega Labs is not liable for any action taken or not taken based on AI Output.'] },
          { type: 'p', text: s('The AI Output generated by Meridian reflects the state of available information at the time of the sweep and may not reflect subsequent developments.') },
        ],
      },
      {
        id: 'tos-4', num: '4', heading: 'Not Professional Advice',
        blocks: [
          { type: 'p', text: [{ strong: 'Meridian is not a professional advisor of any kind.' }, ' The Service is designed to supplement your decision-making process, not replace it. Nothing in the Service constitutes:'] },
          { type: 'ul', items: [
            s('Financial or investment advice — consult a licensed financial advisor'),
            s('Legal advice — consult a licensed attorney'),
            s('Medical or health advice — consult a licensed healthcare provider'),
            s('Career advice — consult a qualified career counselor or recruiter'),
            s('Tax advice — consult a licensed CPA or tax professional'),
          ]},
          { type: 'p', text: s('The fact that Meridian tracks objectives related to your career, finances, health, or other personal matters does not create a professional relationship between you and Solvega Labs. We are a technology company, not a licensed advisor in any field.') },
          { type: 'p', text: s('Meridian is designed to be an outcome-optimized intelligence partner, not a sole decision-maker. Every recommendation the Service generates is one input among many. Your own judgment, and where applicable the judgment of licensed professionals, takes precedence.') },
        ],
      },
      {
        id: 'tos-5', num: '5', heading: 'Subscriptions, Billing, and Refunds',
        blocks: [
          { type: 'p', text: b('Free Trial.', ' New accounts receive a 7-day free trial with access to trial-tier features. No credit card is required during the trial period. At the end of the trial, continued access requires selecting a paid subscription plan.') },
          { type: 'p', text: b('Subscription Plans.', ' Paid subscriptions are billed monthly or annually depending on the plan selected. Prices are displayed at the time of purchase and are subject to change with 30 days notice to existing subscribers.') },
          { type: 'p', text: b("Sweep Credits.", " Sweep credits are one-time purchases that allow additional signal sweeps beyond your plan's included cadence. Credits do not expire. Credits are non-refundable once used.") },
          { type: 'p', text: b('Cancellation.', ' You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period. No partial refunds are provided for unused time within a billing period.') },
          { type: 'p', text: b('Annual Plan Refunds.', ' Annual subscriptions cancelled within 30 days of purchase are eligible for a pro-rated refund for unused months. After 30 days, no refund is provided.') },
          { type: 'p', text: b('Beta User Pricing.', ' Users designated as beta testers who provide structured feedback as agreed are eligible for grandfathered Explorer-tier pricing at the time of public launch. This commitment is made in good faith and subject to the user maintaining active engagement with the beta program.') },
          { type: 'p', text: s("All billing is processed by Stripe, Inc. Solvega Labs does not store payment card information. Stripe's terms and privacy policy apply to payment processing.") },
        ],
      },
      {
        id: 'tos-6', num: '6', heading: 'Acceptable Use',
        blocks: [
          { type: 'p', text: s('You agree not to use the Service to:') },
          { type: 'ul', items: [
            s('Violate any applicable law or regulation'),
            s('Infringe the intellectual property rights of any third party'),
            s('Upload content that is defamatory, harassing, or abusive'),
            s('Attempt to access another user\'s account or data'),
            s('Use automated means to scrape, extract, or harvest data from the Service'),
            s('Use the Service to train or fine-tune any AI or machine learning model'),
            s('Resell, sublicense, or commercially exploit the Service without written authorization from Solvega Labs'),
            s('Attempt to reverse engineer, decompile, or extract the underlying algorithms or models used by the Service'),
            s('Introduce malicious code, viruses, or any software that could harm the Service or other users'),
          ]},
          { type: 'p', text: s('Violation of these terms may result in immediate account suspension or termination without refund.') },
        ],
      },
      {
        id: 'tos-7', num: '7', heading: 'Intellectual Property and Data Ownership',
        blocks: [
          { type: 'p', text: b('Your data.', ' You retain ownership of the objectives, notes, journal entries, and other content you enter into the Service ("User Content"). By using the Service, you grant Solvega Labs a limited license to process your User Content for the purpose of providing the Service to you.') },
          { type: 'p', text: b('No training use.', ' Solvega Labs will not use your User Content to train AI models without your explicit written consent. Your personal objectives, signals, and outcome data are your private information.') },
          { type: 'p', text: b('Aggregated, anonymized data.', ' Solvega Labs may use aggregated, anonymized, non-personally-identifiable data derived from the Service for product improvement, research, and business purposes. This data cannot be used to identify you individually.') },
          { type: 'p', text: b('Meridian platform.', ' The Meridian platform, including its software, algorithms, design, and underlying technology, is the intellectual property of Solvega Labs LLC. You may not copy, reproduce, distribute, or create derivative works from any part of the Service without express written permission.') },
        ],
      },
      {
        id: 'tos-8', num: '8', heading: 'Limitation of Liability',
        blocks: [
          { type: 'p', text: s('TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SOLVEGA LABS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION, ARISING FROM OR RELATING TO YOUR USE OF THE SERVICE.') },
          { type: 'p', text: s("IN NO EVENT SHALL SOLVEGA LABS'S TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATING TO THE SERVICE EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO SOLVEGA LABS IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100).") },
          { type: 'p', text: s('SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES. IF YOU ARE IN SUCH A JURISDICTION, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.') },
          { type: 'p', text: s('THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.') },
        ],
      },
      {
        id: 'tos-9', num: '9', heading: 'Termination',
        blocks: [
          { type: 'p', text: s('Solvega Labs reserves the right to suspend or terminate your account at any time for violation of these Terms, for any conduct that Solvega Labs determines in its sole discretion is harmful to the Service or other users, or for any other reason with or without notice.') },
          { type: 'p', text: s('You may terminate your account at any time by contacting connect@solvega.ai or using the account deletion feature in your settings. Upon termination, your User Content will be deleted within 30 days, subject to any legal retention obligations.') },
          { type: 'p', text: s('Sections 3, 4, 7, 8, and 10 of these Terms survive termination.') },
        ],
      },
      {
        id: 'tos-10', num: '10', heading: 'Governing Law',
        blocks: [
          { type: 'p', text: s('These Terms are governed by the laws of the State of Utah, without regard to conflict of law principles. Any dispute arising from these Terms or the Service shall be resolved in the state or federal courts located in Salt Lake County, Utah, and you consent to the personal jurisdiction of those courts.') },
          { type: 'p', text: s('If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.') },
          { type: 'p', text: s('These Terms, together with the Privacy Policy and Acceptable Use Policy, constitute the entire agreement between you and Solvega Labs regarding the Service and supersede all prior agreements.') },
        ],
      },
    ],
  },

  // ── PRIVACY POLICY ─────────────────────────────────────────────────────────
  {
    id: 'privacy',
    title: 'Meridian Privacy Policy',
    clauses: [
      {
        id: 'pp-1', num: '1', heading: 'What We Collect',
        blocks: [
          { type: 'p', text: b('Account information.', ' When you create an account, we collect your name, email address, and authentication credentials. We do not collect payment card information directly — all payment processing is handled by Stripe, Inc.') },
          { type: 'p', text: b('Objective and goal data.', ' We collect the objectives, notes, target dates, and related context you enter into the Service. This is the core data that powers the Service.') },
          { type: 'p', text: b('Signal and sweep data.', ' When you run a sweep, Meridian collects publicly available information from third-party sources relevant to your objectives. This data is processed and stored to generate your intelligence reports.') },
          { type: 'p', text: b('Usage data.', ' We collect information about how you use the Service, including pages visited, features used, sweep frequency, and interaction patterns. This data is used to improve the Service and is not sold to third parties.') },
          { type: 'p', text: b('Device and technical data.', ' We automatically collect IP address, browser type, operating system, and device identifiers for security, fraud prevention, and service delivery purposes.') },
          { type: 'p', text: b('Calendar data (if connected).', ' If you connect a calendar integration, we access calendar event metadata (titles, dates, times) to provide calendar-aware intelligence. We do not access email content. You can revoke calendar access at any time in your account settings.') },
        ],
      },
      {
        id: 'pp-2', num: '2', heading: 'How We Use Your Information',
        blocks: [
          { type: 'p', text: s('We use the information we collect to:') },
          { type: 'ul', items: [
            s('Provide, operate, and improve the Meridian Service'),
            s('Generate AI-powered intelligence reports, confidence scores, and recommendations'),
            s('Send sweep reports, product updates, and service notifications'),
            s('Detect and prevent fraud, abuse, and security incidents'),
            s('Comply with legal obligations'),
            s('Conduct internal research and product development using aggregated, anonymized data'),
          ]},
          { type: 'p', text: b('We do not sell your personal information to third parties. We do not use your personal objectives or goal data for advertising purposes.') },
        ],
      },
      {
        id: 'pp-3', num: '3', heading: 'Third-Party Services',
        blocks: [
          { type: 'p', text: b('Anthropic.', " The Service is powered in part by Anthropic's Claude AI models. When you run a sweep or use Ask Meridian, your objective context and query are sent to Anthropic's API for processing. Anthropic's privacy policy governs their handling of this data. Anthropic does not retain API inputs to train models by default, subject to their current API terms.") },
          { type: 'p', text: b('Brave Search / NewsAPI.', ' Meridian uses third-party search and news APIs to gather signals relevant to your objectives. Query terms derived from your objective keywords are sent to these services. No personally identifiable information is included in these queries.') },
          { type: 'p', text: b('Stripe.', " Payment processing is handled by Stripe, Inc. We do not store payment card numbers. Stripe's privacy policy governs payment data handling.") },
          { type: 'p', text: b('Supabase.', " Our database and authentication infrastructure is hosted on Supabase. User data is stored in Supabase's managed PostgreSQL environment with row-level security enforced.") },
          { type: 'p', text: b('Resend.', ' Transactional emails (sweep reports, account notifications) are sent via Resend. Your email address is shared with Resend for this purpose.') },
          { type: 'p', text: b('Vercel.', " The Service is hosted on Vercel's infrastructure. Vercel may collect standard web server logs including IP addresses.") },
        ],
      },
      {
        id: 'pp-4', num: '4', heading: 'Data Retention',
        blocks: [
          { type: 'p', text: s('We retain your account data for as long as your account is active. If you delete your account, we will delete your personal data within 30 days, except where retention is required by law or for legitimate business purposes (such as fraud prevention records).') },
          { type: 'p', text: s("Sweep data and signal history are retained for the duration of your account to power the confidence trajectory and prediction log features. This historical data is what makes Meridian's intelligence compounding over time — it is core to the product value.") },
          { type: 'p', text: s('Aggregated, anonymized data derived from your usage may be retained indefinitely for product research purposes, as this data cannot identify you individually.') },
        ],
      },
      {
        id: 'pp-5', num: '5', heading: 'Your Rights',
        blocks: [
          { type: 'p', text: s('Depending on your location, you may have rights regarding your personal data, including:') },
          { type: 'ul', items: [
            [{ strong: 'Access' }, ' — request a copy of the personal data we hold about you'],
            [{ strong: 'Correction' }, ' — request correction of inaccurate data'],
            [{ strong: 'Deletion' }, ' — request deletion of your account and associated personal data'],
            [{ strong: 'Portability' }, ' — request export of your objective and goal data in a structured format'],
            [{ strong: 'Objection' }, ' — object to certain processing activities'],
          ]},
          { type: 'p', text: s('To exercise any of these rights, contact us at connect@solvega.ai. We will respond within 30 days.') },
          { type: 'p', text: s('If you are located in the European Economic Area, you have additional rights under the GDPR. If you are a California resident, you have additional rights under the CCPA.') },
          { type: 'p', text: s('Meridian is not directed at children under 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, contact us at connect@solvega.ai and we will delete it promptly.') },
        ],
      },
    ],
  },

  // ── ACCEPTABLE USE POLICY ──────────────────────────────────────────────────
  {
    id: 'aup',
    title: 'Meridian Acceptable Use Policy',
    clauses: [
      {
        blocks: [
          { type: 'p', text: s('This Acceptable Use Policy ("AUP") governs your use of the Meridian platform operated by Solvega Labs LLC. By using the Service, you agree to this AUP. Violations may result in account suspension or termination.') },
          { type: 'h2', text: 'Prohibited Uses' },
          { type: 'p', text: s('You may not use Meridian to:') },
          { type: 'ul', items: [
            s('Violate any applicable local, state, national, or international law or regulation'),
            s('Infringe, misappropriate, or violate any intellectual property, privacy, or other rights of any party'),
            s('Harass, abuse, threaten, or harm any person'),
            s('Upload, transmit, or store content that is defamatory, obscene, or unlawful'),
            s('Attempt to gain unauthorized access to any part of the Service, another user\'s account, or any connected systems'),
            s('Use automated scripts, bots, or tools to access, scrape, or extract data from the Service'),
            s('Use the Service or its AI Output to train, fine-tune, or improve any artificial intelligence or machine learning model'),
            s('Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code or underlying algorithms of the Service'),
            s('Resell, sublicense, white-label, or otherwise commercially exploit the Service or its outputs without express written authorization from Solvega Labs'),
            s('Introduce malware, viruses, or any other harmful code into the Service'),
            s('Use the Service in any way that could damage, disable, overburden, or impair the Service or interfere with any other party\'s use'),
            s('Use the Service to generate, distribute, or promote misinformation, disinformation, or coordinated inauthentic behavior'),
            s('Circumvent or attempt to circumvent any access controls, rate limits, or usage restrictions'),
          ]},
          { type: 'h2', text: 'AI Output — Responsible Use' },
          { type: 'p', text: s('The AI Output generated by Meridian is provided for informational and planning purposes only. You agree to:') },
          { type: 'ul', items: [
            s('Apply your own judgment before acting on any AI Output'),
            s('Not represent AI Output as professional advice (legal, financial, medical, career, or other)'),
            s('Not share AI Output in ways that could mislead third parties about its nature or reliability'),
            s('Consult appropriate licensed professionals for decisions with significant financial, legal, health, or other consequences'),
          ]},
          { type: 'h2', text: 'Content Standards' },
          { type: 'p', text: s('Any content you enter into the Service must not:') },
          { type: 'ul', items: [
            s('Contain personal information about third parties without their consent'),
            s('Contain confidential information belonging to another party that you are not authorized to share'),
            s('Violate any non-disclosure, confidentiality, or non-compete agreement you are bound by'),
          ]},
          { type: 'h2', text: 'Enforcement' },
          { type: 'p', text: s('Solvega Labs reserves the right to investigate any suspected violation of this AUP. We may, without notice or liability, remove content, suspend access, or terminate accounts that we determine in our sole discretion to be in violation of this AUP or otherwise harmful to the Service, our users, or third parties.') },
          { type: 'p', text: s('Suspected violations may be reported to connect@solvega.ai.') },
        ],
      },
    ],
  },
]
